  - name: check or build image hadoop
    docker_image: path="/etc/ansible/dockerfiles/hadoopo/hadoop" name="my/hadoop" state=present

  - name: Run the hadoop container from image
    docker:
      name: hadoop-main
      image: my/hadoop
      state: started
      ports:
      - "{{ ip_addr_main_serv }}:8088:8088"
